#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  rightBump,      sensorTouch)
#pragma config(Sensor, dgtl2,  rightDRFB,      sensorTouch)
#pragma config(Sensor, dgtl3,  leftDRFB,       sensorTouch)
#pragma config(Sensor, dgtl4,  leftBump,       sensorTouch)
#pragma config(Sensor, dgtl5,  mobileGoalLift, sensorDigitalOut)
#pragma config(Sensor, dgtl6,  clawButton,     sensorTouch)
#pragma config(Sensor, dgtl7,  chainButton,    sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           middleLeftDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftDRFB,      tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port4,           leftDrive,     tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port5,           chainBar,      tmotorVex393_MC29, openLoop, encoderPort, I2C_5)
#pragma config(Motor,  port6,           claw,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rightDrive,    tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port8,           rightDRFB,     tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port9,           middleRightDrive, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma competitionControl(Competition)

//CONSTANTS
#define WHEEL_DIAMETER 4.0 //Inches
#define DRIVE_RATIO 1.0 //Ratio = Out / In
#define TICKS 392.0 //Normal = 627.2; High Speed = 392
#define LCD_CONNECTED false

//supporting files
#include "vex.c" //include vex supporting code
#include "smart_motor.c" //include our custom smart motor library
#include "controller_layout.c" //include the controller layout
#include "basic_functions.c" //include basic functions
#include "pid_functions.c" //include PID functions
//#include "skills.c" //include skills code

//variables
bool skillsEnabled = false; //skills will not run
bool leftStart = false;
ubyte autoChoice = 4; //No autonomous will run

void pre_auton() {
#include "pre_auton.c" //include pre-autonomous code
}

task autonomous() {
//#include "autonomous.c" //include autonomous code
//moveDRFB(90);
setSpeed(leftDRFB, 127, true);
delay(2000);
setSpeed(leftDRFB, 0, true);
setSpeed(chainBar, 127, true);
delay(2000);
setSpeed(chainBar, 0, true);
lowerMobileGoal();
driveInches(60);
raiseMobileGoal();
//turnDegrees(45);
//driveInches(24);
//lowerMobileGoal();
}

task usercontrol() {
#include "driver_control.c" //include driver control code
}
