#pragma config(Sensor, dgtl1,  ,               sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  ,               sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  ,               sensorQuadEncoder)
#pragma config(Motor,  port2,           motor1,        tmotorVex393_MC29, openLoop, encoderPort, dgtl1)
#pragma config(Motor,  port3,           motor2,        tmotorVex393_MC29, openLoop, encoderPort, dgtl3)
#pragma config(Motor,  port4,           motor3,        tmotorVex393_MC29, openLoop, encoderPort, dgtl5)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "smart_motor.c"

float m1, m2, m3;
float rpms[128];

task main() {

	init();
	clearTimer(T1);

	for(int i = 0; i < 128; i++) {
		for(int j = 0; j < 5 * 100; j++) {
			m1 += getRPM(motor1);
			m2 += getRPM(motor2);
			m3 += getRPM(motor3);
			delay(10);
		}
		killAll();
		delay(100);
		rpms[i] = (m1 + m2 + m3) / (3 * 5 * 100.0);
	}
	Write(

}
