#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  encoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  ,               sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  ,               sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           motor1,        tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           motor2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           motor3,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "smart_motor.c"

float sum;
float result[128];

task main() {

	init();

	for(int i = 127; i >= 0; i--) {
		sum = 0;
		setSpeed(motor1, i, true);
		delay(100);
		for(int j = 0; j < 1 * 100; j++) {
			sum += motors[1].rpm;
			delay(20);
		}
		killAll();
		result[i] = sum / (5 * 100.0);
	}

}
