#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           one,           tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port2,           two,           tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port10,          ten,           tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "smart_motor.c"

int ty;
float n,r,a;

task t {
	while(1) {

	}
}

task main() {

	init();

	addSlave(one, ten, 0);
	addSlave(one, two, 1);

	setSlewRate(one, 1);
	//setExternalEncoder(one, I2C_1, 10.);

	setPowerExpander(one, two);

	ty = I2C_1;

	startTask(t);

	setSpeed(one, 127, true);
	while(1) {
		n = nMotorEncoder[motors[0].mPort];
		r = motors[0].rpm;
		a = motors[0].currentDraw;
		delay(20);
	}
}
